name: czr004
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - cmake
  - ninja
  - git
  - cxx-compiler
  - make
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyyaml
  - networkx
  - tqdm
  - statsmodels
  - pytest
  - pybind11
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu124
      - --extra-index-url https://pypi.org/simple
      - torch==2.5.1+cu124
      - torchvision==0.20.1+cu124
      - torchaudio==2.5.1+cu124
      - pillow==10.4.0
