[pytest]
testpaths = tests
pythonpath =
    src
    scripts
norecursedirs =
    .git
    artifacts
    build
    external
    outputs
cache_dir = C:/tmp/pytest-cache-czr004
addopts = --basetemp=C:/tmp/pytest-basetemp-czr004
