"""Command line entrypoint for the Phase2 metrics harness."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from .io import read_jsonl, write_csv
from .schema import normalize_run_row, validate_run_row
from .summary import (
    paired_rows,
    phase1a_gate,
    summarize_by_group,
    summarize_paired_methods,
    summarize_planning_execution,
)


SUMMARY_FIELDS = [
    "map",
    "agents",
    "method",
    "runs",
    "successes",
    "success_rate",
    "ratio_mean",
    "ratio_median",
    "ratio_std",
    "runtime_ms_mean",
    "time_to_first_solution_ms_mean",
    "returned_solutions_count_mean",
    "expanded_nodes_mean",
    "high_level_expansions_mean",
    "low_level_pibt_calls_mean",
]

PAIRED_FIELDS = [
    "map",
    "agents",
    "seed",
    "scen",
    "baseline_method",
    "contender_method",
    "baseline_ratio",
    "contender_ratio",
    "delta_ratio",
    "relative_improvement",
    "contender_better",
]

PE_FIELDS = [
    "planning_execution_step_sec",
    "planning_execution_window",
    "method",
    "runs",
    "successes",
    "ratio_mean",
    "ratio_median",
]


def _format_float(value: float | None) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, float) and not math.isfinite(value):
        return "n/a"
    return f"{float(value):.6g}"


def write_report(
    path: Path,
    *,
    input_path: Path,
    normalized_rows: list[dict],
    schema_error_count: int,
    missing_phase2_fields: dict[str, int],
    paired: dict,
    gate: dict,
    planning_execution_rows: int,
    summary_csv: Path,
    paired_csv: Path,
    planning_execution_csv: Path | None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        handle.write("# Phase2 Metrics Harness Replay Report\n\n")
        handle.write("Status: generated by shared `src/czr004_metrics` harness\n\n")
        handle.write("## Input\n\n")
        handle.write(f"- JSONL: `{input_path}`\n")
        handle.write(f"- rows: {len(normalized_rows)}\n")
        handle.write(f"- schema errors: {schema_error_count}\n\n")

        handle.write("## Phase2 Field Coverage\n\n")
        for field, missing in sorted(missing_phase2_fields.items()):
            handle.write(f"- `{field}` missing/null rows: {missing}\n")
        handle.write("\n")

        handle.write("## Phase1a Replay Gate\n\n")
        handle.write(f"- base groups: {gate['groups']}\n")
        handle.write(f"- LTM group wins: {gate['group_wins']} / {gate['groups']}\n")
        handle.write(f"- maps passing 70% group-win rule: {gate['maps_passing_70pct']} / {gate['maps']}\n")
        handle.write(f"- Pass-A replay: `{gate['pass_a']}`\n\n")

        handle.write("## Paired Statistics\n\n")
        handle.write(f"- paired successes: {paired['paired_successes']}\n")
        handle.write(f"- contender better: {paired['contender_better']}\n")
        handle.write(f"- baseline mean ratio: {_format_float(paired['baseline_ratio_mean'])}\n")
        handle.write(f"- contender mean ratio: {_format_float(paired['contender_ratio_mean'])}\n")
        handle.write(f"- relative improvement: {_format_float(paired['relative_ratio_improvement'])}\n")
        handle.write(f"- sign-test p-value: {_format_float(paired['sign_test_pvalue'])}\n\n")

        handle.write("## Outputs\n\n")
        handle.write(f"- summary CSV: `{summary_csv}`\n")
        handle.write(f"- paired CSV: `{paired_csv}`\n")
        if planning_execution_csv is not None:
            handle.write(f"- planning-and-execution CSV: `{planning_execution_csv}`\n")
            handle.write(f"- planning-and-execution rows: {planning_execution_rows}\n")
        else:
            handle.write("- planning-and-execution CSV: not emitted; no E/X rows in input\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--summary-csv", required=True, type=Path)
    parser.add_argument("--paired-csv", required=True, type=Path)
    parser.add_argument("--planning-execution-csv", type=Path)
    parser.add_argument("--report-md", required=True, type=Path)
    parser.add_argument("--baseline", default="lacam_star")
    parser.add_argument("--contender", default="lacam_star_ltm")
    parser.add_argument("--strict-schema", action="store_true")
    args = parser.parse_args(argv)

    rows = read_jsonl(args.input)
    normalized_rows = [normalize_run_row(row) for row in rows]

    schema_errors: list[str] = []
    for index, row in enumerate(normalized_rows, 1):
        schema_errors.extend(f"row {index}: {error}" for error in validate_run_row(row, args.strict_schema))

    phase2_fields = [
        "time_to_first_solution_ms",
        "returned_solutions_count",
        "expanded_nodes",
        "high_level_expansions",
        "low_level_pibt_calls",
    ]
    missing_phase2_fields = {
        field: sum(1 for row in normalized_rows if row.get(field) is None) for field in phase2_fields
    }

    summary = summarize_by_group(normalized_rows)
    write_csv(args.summary_csv, summary, SUMMARY_FIELDS)

    pairs = paired_rows(normalized_rows, args.baseline, args.contender)
    write_csv(args.paired_csv, pairs, PAIRED_FIELDS)

    planning_execution = summarize_planning_execution(normalized_rows)
    planning_execution_csv = None
    if args.planning_execution_csv is not None and planning_execution:
        planning_execution_csv = args.planning_execution_csv
        write_csv(planning_execution_csv, planning_execution, PE_FIELDS)

    paired = summarize_paired_methods(normalized_rows, args.baseline, args.contender)
    gate = phase1a_gate(normalized_rows, args.baseline, args.contender)
    write_report(
        args.report_md,
        input_path=args.input,
        normalized_rows=normalized_rows,
        schema_error_count=len(schema_errors),
        missing_phase2_fields=missing_phase2_fields,
        paired=paired,
        gate=gate,
        planning_execution_rows=len(planning_execution),
        summary_csv=args.summary_csv,
        paired_csv=args.paired_csv,
        planning_execution_csv=planning_execution_csv,
    )

    if schema_errors:
        preview = "\n".join(schema_errors[:20])
        extra = "" if len(schema_errors) <= 20 else f"\n... {len(schema_errors) - 20} more"
        raise ValueError(f"schema validation failed:\n{preview}{extra}")

    print(
        "phase2_metrics "
        f"rows={len(normalized_rows)} groups={len(summary)} pairs={len(pairs)} "
        f"schema_errors=0 report={args.report_md}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
